### DISCUSSION TITLE
Feature request: simplify configuration using templates

### DISCUSSION THREAD

**Discussion by git-developer** [BlackZork/mqmgateway#24] [Ideas]
Consider a real-world scenario with 2 Modbus networks:
* Network N1 has 15 devices of model A with 20 read-only registers
* Network N2 has 10 devices of model B with 10 read-only registers

A configuration for a simplified case with 2 devices per network and 2 registers per device could look like this:
<details>
  <summary>Example configuration</summary>

```yaml
mqtt:
  client_id: mqm-client-1
  broker:
    host: broker
  objects:
    # device of model A, slave 17
    - topic: sensors/basement/a-17/energy
      network: basement
      slave: 17
      state:
        register: 28
        count: 2
        converter: std.divide(100)
    - topic: sensors/basement/a-17/voltage
      network: basement
      slave: 17
      state:
        register: 36
    # device of model A, slave 18
    - topic: sensors/basement/a-18/energy
      network: basement
      slave: 18
      state:
        register: 28
        count: 2
        converter: std.divide(100)
    - topic: sensors/basement/a-18/voltage
      network: basement
      slave: 18
      state:
        register: 36
    # device of model B, slave 1
    - topic: sensors/roof/b-01/temperature
      network: roof
      slave: 1
      state:
        register: 1
    - topic: sensors/roof/b-01/humidity
      network: roof
      slave: 1
      state:
        register: 2
    # device of model B, slave 2
    - topic: sensors/roof/b-02/temperature
      network: roof
      slave: 2
      state:
        register: 1
    - topic: sensors/roof/b-02/humidity
      network: roof
      slave: 2
      state:
        register: 2
```
</details>

Imagine how this file would look like in the real-world scenario... I'd like to reduce redundancy and have a few ideas:

1. Topic Template: a named group with mappings MQTT topic <-> Modbus
2. Slave List: a list of slaves with a reference to a topic template
3. A base topic on `mqtt` level

The following example shows how the configuration above could look like:

```yaml
mqtt:
  client_id: mqm-client-1
  broker:
    host: broker
  base-topic: sensors
  topic-templates:
    device-a:
      - topic: energy
        state:
          register: 28
          count: 2
          converter: std.divide(100)
      - topic: voltage
        state:
          register: 36
    device-b:
      - topic: temperature
        state:
          register: 1
      - topic: humidity
        state:
          register: 2
  slaves:
    - network: basement
      slave: 17
      topic: basement/a-17
      template: device-a
    - network: basement
      slave: 18
      topic: basement/a-18
      template: device-a
    - network: roof
      slave: 1
      topic: roof/b-01
      template: device-b
    - network: roof
      slave: 2
      topic: roof/b-02
      template: device-b
```

* The child nodes of `topic-templates` (e.g. `device-a`) are of the same type as the existing `objects` node.
* A slave node can be transformed to an `objects`node by "dereferencing" the template

**Comment by BlackZork** [comment]
Yes, I already created a 'templates' branch which is abandoned for a long time because of lack of time, so there is nothing interesting in that branch.

I have slightly different requirements for template support listed below, but I think this idea is compatible with yours.

 - ideally there should be one template per device. I should be able to import it, assign a slave id and then see all the data published on mqtt side.
 - default topic names in a template should follow device documenation. When I see data on mqtt side I should be able to easily correlate it with device manual.
 - I should be able to turn off default "publish all" mode and manually specify which topics should be published
 - I should be able to override the default topic name, refresh time, converter or add a new topic with different register configuration.
 - templates should be able to extend other templates. I have some devices that differs only by numer of registers for input or output. Documentation is mostly the same.
 - I should be able to easily convert existing objects definition into a template
 
 This is how I think template should work:

 ```yaml
# it should be possible to import this part from mutiple files in some 'templates' directory
object_templates:
	- name: Energy_Meter_Model_A
      # this part is exactly the same as mqtt.objects declarations
      objects:
      - topic: model_name
        state:
          register: 7
          count: 8
          # not implemented yet
          refresh: once
          converter: std.string
      - topic: energy
        state:
          register: 28
          count: 2
          converter: std.divide(100)
      - topic: voltage
        state:
          register: 36
	- name: Energy_Meter_Model_B
	  objects:
        - topic: temperature
          state:
            register: 1
        - topic: humidity
          state:
            register: 2
            
mqtt:
  ....
  objects:
    - from_template: Energy_Meter_Model_A
      # short version for network and slave id - not implemented yet
      slave: basement.10
      refresh: 100ms
      name: basement/a-10
	    # publish only those topics
      topics:
       # this one will be published as default basement/a-10/my_energy
       # with overriden attributes
       - name: energy
         new_name: my_energy
         converter: std.divide(1000)
	   # this one will be published as default basement/a-10/voltage
       - voltage

	  # this will publish all topics defined in template
	  # useful for self-defined templates that expose only part of device data.
	  # as in your example
    - from_template: Energy_Meter_Model_B
      name: basement/b-11
      slave: basement.11

    # other untemplated objects as it is defined now
    # this example extends already templated slave
    - topic: basement/a-10/alternative
      network: basement
      slave: 10
      state:
        register: 30
        count: 2
        converter: std.divide(100)	  
```      

This is just an idea, I did not verify it in any way and there could be some obstacles or changes
needed for implmementation. Configuration above is hand-written and may be buggy.

**Reply by BlackZork** [reply]
....another thing that I did not notice is that there are cases when a single devices should be mapped to different topics without common prefix. For example:

```yaml
mqtt:
  objects:
     - topic: bedroom/light/main
       state:
         register: rtu.1.1
       commands:
         - name: set
           register: rtu.1.1         
     - topic: bedroom/kitchen/main
       state:
         register: rtu.1.2
       commands:
         - name: set
           register: rtu.1.2
```

In this case one device handles switches or sensors from different entities. I cannot use common `name` to prefix topics in template. Maybe an optional `topic_prefix` or `topic_base` instead of `name` would be better. If it is empty, then I have to set full topic path in `new_name` (named `publish_as` or `rename_to` as in my later replies)

**Reply by git-developer** [reply]
(I assume you meant to write `kitchen/light/main` instead of `bedroom/kitchen/main`.)

I favor `publish_as` over `rename_to`, because at this point we want specify a changed MQTT topic and not the name of a mapping entry.

I'm a little bit confused if the "common prefix" idea should belong into the template section, into the device section or both. Which of the following examples are useful from your perspective?

#### (1) No base topics, topic redefinition
```yaml
object_templates:
  - name: Switch_Group_Model_A
    objects:
      - topic: switch-1
      - topic: switch-2
mqtt:
  objects:
    - from_template: Switch_Group_Model_A
      slave: rtu.1
      topics:
        - topic: switch-1
          publish_as: bedroom/light/main
        - topic: switch-2
          publish_as: kitchen/light/main
```
Result: `bedroom/light/main` and `kitchen/light/main`

#### (2) Device base topic
```yaml
object_templates:
  - name: Switch_Group_Model_A
    objects:
      - topic: bedroom/main
      - topic: kitchen/main
mqtt:
  objects:
    - from_template: Switch_Group_Model_A
      slave: rtu.1
      name: light
```
Result: `light/bedroom/main` and `light/kitchen/main`

#### (3) Device base topic and template base topic
```yaml
object_templates:
  - name: Switch_Group_Model_A
    topic: light
    objects:
      - topic: bedroom/main
      - topic: kitchen/main
mqtt:
  objects:
    - from_template: Switch_Group_Model_A
      slave: rtu.1
      name: house-1
```
Result: `house-1/light/bedroom/main` and `house-1/light/kitchen/main`

#### (4) No template base topic, no topic redefinition
```yaml
object_templates:
  - name: Switch_Group_Model_A
    objects:
      - topic: bedroom/light/main
      - topic: kitchen/light/main
mqtt:
  objects:
    - from_template: Switch_Group_Model_A
      slave: rtu.1
      name: house-1
```
Result: `house-1/bedroom/light/main` and `house-1/kitchen/light/main`

**Reply by BlackZork** [reply]
My point was that `mqtt.objects.from_template.name` should be optional, because `publish_as` could be different for every topic.
I think that `name` is too generic. I would use `prefix`, `topic_prefix` or `topic_base` instead.

I do not think topic names in template are natrually tied to device, so only example (1) makes sense.

**Comment by git-developer** [comment]
This looks indeed as if it is compatible with my requirements.

Some thoughts:
* An entry of the `objects` list is a mapping between Modbus and MQTT and could be named "mapping".
* The `topics` list contains more than MQTT topics, it contains mappings and could thus be named `mappings`.
* Each mapping could get an optional `name` (mapping name, not topic name), defaulting to the `topic` value. This allows to omit the `new_name` attribute, e.g.
  ```yaml
  mqtt:
    ...
    objects:
      - from_template: Energy_Meter_Model_A
        # short version for network and slave id - not implemented yet
        slave: basement.10
        refresh: 100ms
        name: basement/a-10
        # publish only those topics
        mappings:
        # this one extends mapping entry "Energy_Meter_Model_A.energy"
        # and will be published as default basement/a-10/my_energy
        # with overriden attributes
        - name: energy
          topic: my_energy
          converter: std.divide(1000)
        # this one will be published as default basement/a-10/voltage
        - voltage
  ```
* The `topics` (=`mappings`) list seems to have "include" (whitelist) semantics in your example. Depending on your needs, you could refine semantics to be one of
    * include: use mapping exactly as defined in the template
    * exclude: do not publish
    * override: merge with mapping from template and then include
    * replace: exclude mapping from template, instead include this one

**Reply by BlackZork** [reply]
Thanks for your comments.

`mapping` broke my requirement that there should be an easy way to convert existing 'objects' declaration into a template.

I do not like `new_name` attribute too, maybe `publish_as` or `rename_to` sounds better.

I do not think that we need any other ways of using a template besides full include variant or topic list override variant. The first will be common for self-made templates, the second one for some central template repository that you can use. Would rather add other ways only when there is a new requirement from real world usage.

**Comment by git-developer** [comment]
`poll_groups` are often related to a device model, so they should be useful on the template level, too:

```yaml
object_templates:
  - name: Energy_Meter_Model_A
    poll_groups:
      - register: 1
        count: 20
     # this part is exactly the same as mqtt.objects declarations
    objects:
    ...
```

**Reply by BlackZork** [reply]
Yes, that is a good idea, but makes sense only if you use template as whole. I would rather keep it in the `modbus` config section with some improvements:

```yaml
pull_groups:
    # first way: common group for range of slaves, can be specified as 1,2,3,4,5 too
  - slaves: 1..5
    register: 1
    count: 20
    # second way: group for all topics that use specific template
  - device: Energy_Meter_Model_A
    register: 1
    count: 20
```

**Comment by fencepost-error** [comment]
Just saw this discussion when I was going to post more or less the same request, at the moment if you've got multiple devices of the same type you need to cut&paste the same config over and over again and then manually edit per-device settings like the device ID, it'd be really nice to be able to have something like a #include of libraries of devices, so you define something like "temperature_meter" once in a library definition and then include that into your config file.  As an example, I have some Eastron energy meters which have something like three A4 pages of registers per device, and then half a dozen devices, that's a lot of repeated definitions and locations to edit on a per-device basis.

This also means people could contribute configs they've created for common devices rather than everyone having to reinvent the wheel themselves.

I'm not fussed over what form it takes as long as I can avoid having to hand-code in settings for each device individually.  The [outline in this reply](https://github.com/BlackZork/mqmgateway/discussions/24#discussioncomment-6555479) seems to be fine.

**Comment by fencepost-error** [comment]
So there may be a no-code way to do templates, as long as yaml-cpp supports !include.  Let's say you have the power meters I've been using as an example in another thread, for which a template register entry might be:
```
    - topic: XX/voltage
      network: modbustcp
      slave: YY
      state:
        converter: std.float32()
        register: 1
        register_type: input
        count: 2
```
Then for each new device you want to add, say in this case 'mains' with address 10, you'd use something like `cat template.yaml | sed s/XX/mains/g | sed s/YY/10/g > mains.yaml` and then !include mains.yaml into the main config.yaml. That gives you templates with no extra coding required for mqmgateway.

**Reply by BlackZork** [reply]
Good hack:-) 

Templates will be implemented here sooner or later :-)

**Reply by fencepost-error** [reply]
More like a kludge :-).  I'd actually be perfectly happy with the !include fix, it gets the job done without requiring a lot of extra work.  Anyway, let me see what sort of !include support there is...

**Comment by fencepost-error** [comment]
Hmm, so it looks like yaml-cpp doesn't support !include.  However it's still doable: modmqtt.cpp has `YAML::Node config = YAML::LoadFile(targetPath);`.  Change this to `YAML::Node config = YAML::Load(yamlData);` where yamlData is generated with something like:
```
allocate yamlData buffer;
open config file for read;
if configfile next value != "!include"
  copy next value to yamlData;
else
  realloc yamlData if necessary;
  read filename from !include into yamlData;
close config file;
YAML::Load(yamlData);
```
Let me know if that's of interest and I can implement it, it's effectively just a preprocessor on the YAML file that adds support for !including other files as templates.

**Reply by fencepost-error** [reply]
And thinking about it a bit more, you could specify the two args needed to change the template without needing to create lots of custom files, so something like:
```
!include template.yaml foo 10
!include template.yaml bar 11
!include template.yaml baz 12
```
would include the template file three times, changing the topic to 'foo' and address to 10 in the first one, 'bar' and 11 in the second, and 'baz' and 12 in the third.  So that's more or less templates implemented, just not the way you'd expect :-).

**Reply by BlackZork** [reply]
If you do not need to alter anything but slave id then consider something like this:

1.Move all topics related to _Mydevice_ from config.yaml to _mydevice.yaml_, remove `slave: X` there.
2. Rename config.yaml to config.yaml.in
3. Add to config.yaml.in, in mqtt.objects section:

```yaml
 - from_template: mydevice
   slave: 1
```

4. Parse config.yaml.in in some python script, loop on objects and when you see a "from_template" instead of a "topic" add yaml data from mydevice.yaml in this place, merging each topic with `slave: 1`
5. Output modified yaml to config.yaml

In python it is a few lines of code. Much easier than patching mqmgateway.
Besides I have a feeling that you will not have to change much when mqmgateway gets support for templates.

**Reply by fencepost-error** [reply]
I was going to do it in a shell script with sed doing the work (as per the original example earlier), mostly because I don't know Python that well and it's simple enough that you don't need anything fancy.  The reason for mentioning the !include hack is that if you were going to implement it in mqmgateway itself then its presumably a lot less work doing it that way than having to process a lot of YAML to handle templates.  The !include hack is really just a preprocessor where there's no need to do any extra work at the YAML level.

**Reply by fencepost-error** [reply]
So this low-tech approach to templates actually works surprisingly well, the following is a basic shell script that takes a header file and then uses one or more template files to build the config file.  Each template file only needs to be created once for a modbus device, after which you can use the script to apply it to any number of devices.  As a test I ran it for three Eastron power meters and it worked the first time (I'm still waiting for something to catch fire or explode).

```
#!/bin/bash
# Build a mqmgateway config file from template files.

HEADER_FILE="config_header.yaml"
OUTPUT_FILE="config.yaml"

# Create an output file from a template file.  This just strips comments
# and inserts the topic, network name, and address at the appropriate
# locations.

compile_template()
	{
	TEMPLATE_FILE=$1
	TOPIC=$2
	NETWORK=$3
	ADDRESS=$4

	cat "${TEMPLATE_FILE}".yamlt | sed '/^#/d' | sed s/XXXX/"${TOPIC}"/g | sed s/YYYY/"${NETWORK}"/g | sed s/ZZZZ/"${ADDRESS}"/g >> "${OUTPUT_FILE}"
	}

# "Compile" the input files into the config file.  The argument order
# is 'template_file topic_name network address'.

if [ -f ${OUTPUT_FILE} ] ; then
	rm ${OUTPUT_FILE} ;
fi
cp ${HEADER_FILE} ${OUTPUT_FILE}

compile_template eastron grid switchboard 10
compile_template eastron non_backup switchboard 11
compile_template eastron backup switchboard 12
```
Then just
```
sudo cp config.yaml /etc/modmqttd/config.yaml
sudo systemctl restart modmqttd
```
and you're up and running.

**Reply by fencepost-error** [reply]
Here's the latest update of mkconfig which has been improved to apply the config as well as generate it unless you run in -d debug mode, add some error checking of templates, and a few other changes.  This makes it much, much easier to deal with multiple devices, you just define the template once and then instantiate as many as you want with mkconfig.

```
#!/bin/bash
# Build a mqmgateway config file from template files and apply it to
# modmqttd.  Arguments:
#
# -d = debug mode, generate the config file without applying it.
# -v = verbose mode, show each template generation.

HEADER_FILE="config_header.yaml"
OUTPUT_FILE="config.yaml"
DEBUG=0
VERBOSE=0

# Process any optional flags before the args.

while getopts "dv" options ; do
	case "${options}" in
		d) DEBUG=1 ;;
		v) VERBOSE=1 ;;
	esac
done
shift $(( OPTIND - 1 ))

# Check for common problems in template files.  Using a register value of 0
# is particularly problematic since it gets converted to -1, which makes the
# resulting error message look like it's an error return value from a
# libmodbus function.  Using invisible-to-the-editor tabs is also a problem,
# better to catch this at this stage than later when they're in the config
# file.

for file in *.yamlt ; do
	if [ "$(grep -c '^\s*register:\s*0\b' $file)" -gt 0 ] ; then
		echo "Template $file uses 0-based registers, should be 1-based" >&2 ;
		exit 1 ;
	fi
	if [ "$(grep -c $'\t' $file)" -gt 0 ] ; then
		echo "Template $file contains tab characters, should be spaces" >&2 ;
		exit 1 ;
	fi
done

# Create an output file from a template file.  This just strips comments
# and inserts the topic, network name, and address at the appropriate
# locations.

compile_template()
	{
	TEMPLATE_FILE=$1
	TOPIC=$2
	NETWORK=$3
	ADDRESS=$4

	if [ $VERBOSE -eq 1 ] ; then
		echo "Creating topic ${TOPIC} from template ${TEMPLATE_FILE}.yamlt" ;
	fi

	if [ ! -f "${TEMPLATE_FILE}".yamlt ] ; then
		echo "Template ${TEMPLATE_FILE}.yamlt not found" >&2 ;
		exit 1 ;
	fi

	cat "${TEMPLATE_FILE}".yamlt | sed '/^#/d' | sed s/XXXX/"${TOPIC}"/g | sed s/YYYY/"${NETWORK}"/g | sed s/ZZZZ/"${ADDRESS}"/g >> "${OUTPUT_FILE}"
	}

# "Compile" the input files into the config file.  The argument order
# is 'template_file topic_name network address'.

if [ -f ${OUTPUT_FILE} ] ; then
	rm ${OUTPUT_FILE} ;
fi
cp ${HEADER_FILE} ${OUTPUT_FILE}
echo "# Everything beyond this point is auto-generated by mkconfig.sh." >> "${OUTPUT_FILE}"
echo "# Any changes will be overwritten on the next rebuild." >> "${OUTPUT_FILE}"

compile_template eastron grid switchboard 10
compile_template eastron non_backup switchboard 11
compile_template eastron backup switchboard 12

compile_template waveshare_io waveshare_io basement 20

compile_template pulse_count water basement 21

compile_template temp_humid network basement 10

compile_template temp_humid annex garage 10
compile_template temp_humid car garage 11
compile_template temp_humid deck garage 12

compile_template water_level water_tank garage 20

compile_template reactor_rod_control nuclear_reactor sub-basement 10
compile_template reactor_power_output nuclear_reactor sub-basement 11

# If we're running in debug mode only, don't apply the changes

if [ $DEBUG -eq 1 ] ; then
	exit 0 ;
fi

# Install the new config file and restart modmqttd.  We need to pause
# for a second after the restart to allow modmqttd time to initialise.

sudo cp config.yaml /etc/modmqttd/config.yaml
sudo systemctl restart modmqttd
sleep 1
sudo systemctl status modmqttd | less
```

**Comment by fencepost-error** [comment]
And a general comment, @BlackZork would you consider taking contributions from users for scripts and templates?  Happy to contribute mkconfig and the templates I've done so far, perhaps into a /contrib directory for anyone who wants to use them.  Writing these things only once would make it a lot easier for any other users with the same device.

**Reply by BlackZork** [reply]
It is great that you have managed to create these scripts for configuration management. I do not think it is a good idea to include them in the mqmgateway repo, mainly because template support in yaml configuration is quite high on my priority list. If you want to create your own repo with these scripts, I will certainly link to it from the github front page.

As for templates for specific devices, I am afraid it is impossible for the following reasons:

1. AGPL licence does not make sense for templates for me. I think the template repository should force templates to have a MIT license, or if you do not care then there should be a requirement that a license name or text should be included in the template file.
2. Legal issues - some device vendors do not allow Modbus register documentation to be published. Sooner or later you will have to remove the template on request. Git repository is not the best tool to remove something without a trace. 

Database organization, validation and quality - I haven't thought this through enough yet. I want to do my best to make template support work for as many scenarios as I can think of. If I get it wrong, and people start submitting their work, it will be very hard to fix design errors without breaking someone's setup.

**Reply by fencepost-error** [reply]
OK, I'll create a repo, probably not for a few weeks though because I'll be travelling a lot before then.  If anyone else is in a hurry to get templates before then... hmm, Github still hasn't re-enabled private messaging yet has it?

In terms of the license, I hadn't even thought about that one, the templates are just something I put together to make things easier for me, and thought others might find them useful.  I'm happy to make them public domain/CC0, I've written other much more complex stuff that's GPL'd but these are just small text files that anyone can use.

In terms of legal issues, all the data in them is taken from public, freely-available docs, and apart from the Eastrons they're all endlessly-copied devices off Aliexpress so I don't see any legal issues (I wrote to one of the vendors once offering them some code I'd written to talk to the device and never got a reply, so I don't think they care much).  I do see your point about quality control and organisation though.... I saw it more as a "use these if you find them useful" rather than a "guaranteed correct template for hardware device X".

I'll set up a repo in a few weeks when I get back and see how it goes, if there's only a handful of contributions with few changes required then the problem will more or less have solved itself.

In any case so far it's been great running this stuff with mqmgateway, just four templates are generating something like 25kB of config file, and every time I make a change (e.g. getting input register reads wrong because of confusing documentation) I only have to change one location in a template rather than editing every location where it occurs in the config file.

**Reply by fencepost-error** [reply]
Finally got around to creating the repo, it's [here](https://github.com/fencepost-error/Templates-for-MQMGateway).  The script has evolved a bit, it now does basic error checking, performs DNS lookups and inserts the appropriate IP addresses into the YAML, generates config.yaml, and applies it to modmqttd.

The next step will be to also generate the YAML required by Home Assistant as part of the same process so you can go from templates -> MQMGateway + Home Assistant in a single step without having to hand-edit a large amount of YAML.  It should also make changes much easier when the script compiler does all the work.

**Reply by fencepost-error** [reply]
And it now does Home Assistant as well, so there's a single tool to go from Modbus device+register -> MQMGateway -> HA.  The output is two lots of YAML, one to use with MQMGateway, one to use with Home Assistant.  The one remaining hurdle is HA Cards, it looks like you need to go to JSON for those (ugh).

**Comment by BlackZork** [comment]
I think for both use cases described here templates are overkill. As first step I would add support for multiple slave declaration like this:

```yaml
modbus:
  networks:
  - name: basement
    slaves:
      - address: 1,2,3,5,18-24
        poll_groups:
          - register: 1
            register_type: input
            count: 50
mqtt:
  client_id: mqm-client-1
  broker:
    host: broker
  objects:
    - topic: sensors/${network}/a-${slave_address}/energy
      network: basement
      slave: 1,2,3,5,18-24
      state:
        register: 28
        count: 2
        converter: std.divide(100)
```

If slave is defined as a list of addresses in mqtt section, then you will have to add `network` and `slave_address` placeholders in topic.

It is very easy to implement and easier to use than completely new template language. What do you think?

**Reply by fencepost-error** [reply]
Nice, that would pretty much solve the problem I was trying to deal with.  The only issue is the naming, having topics that hardcode the device address into the name rather than having a name that identifies what's being reported will make it a bit confusing, e.g. where I had .../switchboard/grid your version would have .../switchboard/a-11 or similar.  Not sure what the best way to handle this is, you mentioned that the parser you're using doesn't support maps so maybe:
```
      - address: 1,2,3,5,18-24
         description: grid, solar, non-backup, ....
````
where each 'description' entry matches the 'address' entry at the same index.

**Reply by BlackZork** [reply]
That is not a big problem, I can add a name to slave properties:

```yaml
modbus:
  networks:
  - name: basement
    slaves:
      - address: 1
        name: grid
      - address: 2
        name: solar
      - address: 3
        name: non-backup
      - address: 1-3
        poll_groups:
          - register: 1
            register_type: input
            count: 50
mqtt:
  client_id: mqm-client-1
  broker:
    host: broker
  objects:
    - topic: sensors/${network}/a-${slave_name}/energy
      network: basement, other
      slave: 1-3
      state:
        register: 28
        count: 2
        converter: std.divide(100)
```

This config will create 6 objects - three for the `basement` network and three for the `other` network

Of course you will have to set a name for all slaves that are specified in mqtt.objects[x].slave if topic has a `slave_address`/`slave_name` placeholder. Same for multiple networks.
