### DISCUSSION TITLE
Feedback for v1.4.0

### DISCUSSION THREAD

**Discussion by git-developer** [BlackZork/mqmgateway#34] [General]
I just updated from v1.2.0 to v1.4.0 and want to give a little feedback.

General feedback: everything still works fine after the update.

### Configuration Migration
`poll_groups` have been moved.

v1.2.0:
```yaml
modbus:
  networks:
    - name: foo
      address: "192.168.0.10"
      port: 502
      poll_groups:
      - { register: 1.1,     count: 48, register_type: input }
      - { register: 1.259,   count: 48, register_type: input }
      - { register: 1.64513, count:  4 }
```

v1.4.0:
```yaml
modbus:
  networks:
    - name: foo
      address: "192.168.0.10"
      port: 502
      slaves:
        - address: 1
          poll_groups:
            - { register: 1,     count: 48, register_type: input }
            - { register: 259,   count: 48, register_type: input }
            - { register: 64513, count:  4 }
```

The debug log shows that the registers are still requested once as group with the new configuration.

### Error message
The log contains an error message on application start:
```
mqm-garage  | 2024-Jan-18 20:04:47.543524: [INFO]       modmqttd is starting
mqm-garage  | 2024-Jan-18 20:04:47.546046: [INFO]       Added converter plugin std
mqm-garage  | 2024-Jan-18 20:04:47.600081: [INFO]       Connecting to 192.168.0.10:502
mqm-garage  | 2024-Jan-18 20:04:47.600300: [INFO]       Minimum delay before poll set to 0ms
mqm-garage  | 2024-Jan-18 20:04:47.600411: [ERROR]      Unknown messsage received, ignoring
mqm-garage  | 2024-Jan-18 20:04:47.600505: [INFO]       modbus: connecting
mqm-garage  | 2024-Jan-18 20:04:47.601202: [INFO]       modbus: connected
mqm-garage  | 2024-Jan-18 20:04:47.601350: [INFO]       Waiting for mqtt network to become online
mqm-garage  | 2024-Jan-18 20:04:47.607808: [INFO]       Connecting to broker:1883
mqm-garage  | 2024-Jan-18 20:04:47.607956: [INFO]       Waiting for mqtt network to become online
mqm-garage  | 2024-Jan-18 20:04:47.614004: [INFO]       Connection estabilished
```

As far as I can tell, this message has no negative impact.

**Comment by git-developer** [comment]
A comment on the following example from the [README](https://github.com/BlackZork/mqmgateway#mqtt-section):

```yaml
slaves:
  - address: 1
    poll_groups:
      - register: 1
        register_type: input
        count: 20
[...]           
state:
  - name: humidity
    register: 1.18
    register_type: input
    count 5
```

> poll group will be extended to count=23


Some of my devices have a built-in count limit. When `count` is above, they don't send a response. This limit is model specific and cannot be determined automatically, it is described in the device manual. When modmqttd extends `count` as described above, this could result in `count` being too large.

I guess this is not a real problem because the user can change the configuration so that limit will not be exceeded. S/he just has to be aware of this behavior.
