### DISCUSSION TITLE
Dealing with buggy modbus implementations

### DISCUSSION THREAD

**Discussion by fencepost-error** [BlackZork/mqmgateway#63] [Q&A] [answered]
I'm sure this will come as a profound shock :-), but there are some pretty buggy modbus implementations out there, including one that's more like a modbus emulator than an actual modbus implementation in that it responds to particular modbus byte sequences with valid-looking responses but doesn't seem to contain a real modbus implementation that can process commands.

The first aspect of this is that you have to read all 13 holding registers at once to get the few that are valid, so the read command has to be:

```
0x 03 00 01 00 0D
```

Trying to read individual registers or subgroups returns garbage messages.  It looks like it's possible to deal with this using poll groups:

```
slaves:
   - address: x
     poll_groups:
      - register: 2
        register_type: input
        count: 13

state:
  - name: cabinet_temperature
    register: 2
    register_type: input
  - name: cabinet_humidity
    register: 5
    register_type: input
  - name: target_humidity
    register: 6
    register_type: input
```

and then when you read the three registers that are useful will MQMGateway read all 13 registers or will it restrict the range to only 2-6 since the others aren't being used?

**Comment by fencepost-error** [comment]
The second problem is around coils and is even messier, and I'm not sure how to handle this one: The only coil read command it recognises is:

```
0x 01 00 01 00 20
```

i.e. read 32 coils starting at 1.  Actually you can ask for 3 coils, 11 coils, 19 coils, or the full 32, but you always get 32 coils back so it's best to ask for 32 and not get problems due to incorrect message lengths.

However the bits set for various coils aren't reliable so the only thing you can reliably say is all-zero bits -> device off, some non-zero bits -> device on.

In terms of handling this, can you also use the poll-group trick for coils? So:

```
slaves:
   - address: x
     poll_groups:
      - register: 2
        register_type: coil
        count: 32

state:
  - name: device_on
    register: 23
    register_type: coil
```

The given coil, 23, seems to reliably track the on/off state.  I assume the register in this case is the coil number, which is byte 3, bit 6, which is coil 22, or 23 when the count is 1-based.

**Comment by fencepost-error** [comment]
The third problem is around writing coils because they've got the numbering wrong so the coil read numbers don't match the coil write numbers, but I'll leave dealing with that until I know I can read them.

**Comment by BlackZork** [comment, marked as answer]
Poll group should be used as declared. It may be extended if a register/count definition overlaps with it. But it is never shrink.

Run gateway with debug log level. It will print final poll specifications after all merges.

With trace level you can see every modbus read call.

**Reply by fencepost-error** [reply]
I can't find anything in the docs about logging or debug levels, from a quick look at the source code it looks like it uses Boost logging but I haven't found the code section yet that enables or configures it... how is logging enabled?

Update: This isn't critical since I got it working with a bit of trial and error, but it would probably be good to cover it in the docs for future reference :-).

**Reply by BlackZork** [reply]
Logging documentation added in  20b124d6

**Comment by fencepost-error** [comment]
A summary for anyone else who may run into this, the poll-group trick solves the problem.  So in the ```modbus:``` section you need to define a poll group for anything that needs to be read in a single block.  In this case registers 1-13 need to be read in one go, and coils 1-32 need to be read in one go:

```
      slaves:
        - address: 1
          poll_groups:
            - register: 2
              register_type: holding
              count: 13
            - register: 2
              register_type: coil
              count: 32
```

Then in the ```state:``` section you need to read at least one value from the group to trigger the whole-group read, e.g:

```
    - topic: hvac/cabinet_temperature
      network: basement
      slave: 1
      state:
        converter: std.divide(10,1)
        register: 2
        register_type: holding
    - topic: hvac/device_on
      network: basement
      slave: 1
      state:
        register: 24
        register_type: coil
```

A debugging hack for coils when it's not clear which coil number corresponds to which bit is to define them as a series of MQTT topics:

```
    - topic: test/bit1
      [...]
      state:
        register: 1
        register_type: coil
    - topic: test/bit2
      [...]
      state:
        register: 2
        register_type: coil
      [...]
```

and then you can toggle various things and see which of the bits change.

It might be useful to mention this slightly nonstandard use of poll groups in the docs, it's obvious in hindsight but perhaps not when you're trying to figure out how to get data from a buggy device.  In particular the broken way this one does coil reads would be impossible to handle without the magic of poll groups to help you.
