### DISCUSSION TITLE
A note on dealing with reversed-logic devices, e.g. normally-closed (NC) relays

### DISCUSSION THREAD

**Discussion by fencepost-error** [BlackZork/mqmgateway#64] [Show and tell]
In case this is useful to others, a quick note on dealing with reverse-logic devices like NC relays where on is off and off is on, the recently-added map capability is very useful for this.  In the ```state:``` section for the entity just put:
```
      state:
        register: <whatever>
        register_type: coil
        converter: std.map( '{ 0:1, 1:0 }' )
```
and the MQTT value will now match the state of the entity as you'd expect to see it rather than the reversed state you'd normally see.
