### DISCUSSION TITLE
Publishing the value directly to {topic} instead of {topic}/state

### DISCUSSION THREAD

**Discussion by tinooo** [BlackZork/mqmgateway#90] [Q&A] [answered]
I've a very basic question and am not sure if I'm missing something.

When having a very basic config such as:
```
- topic: topic1
      state:
        register: tcp.1.16
        register_type: input

```
my result will be like this:
topci1/state = value.

Is there any option, to ditch the "state" and have my value directly written to topic1?
