### ISSUE TITLE
The named list example in the README is wrong

### ISSUE THREAD

**Issue by molnarg** [BlackZork/mqmgateway#12]
In the README, this is the example for generating a JSON object (key-value map) to publish
```
state:
  registers:
    - name: humidity
      register: net.1.12
      register_type: input
      # optional
      converter: std.divide(100,2)
    - name:  temp1
      register: net.1.13
      register_type: input
```

But this in fact generates a list. From [a test case](https://github.com/BlackZork/mqmgateway/blob/54b47a32c70cc39de991d3e0766ade62402b4f6d/unittests/mqtt_state_map_conv_tests.cpp#L35), the correct syntax is:

```
      state:
        - name: sensor1
          register: tcptest.1.2
          register_type: input
          converter: std.divide(100,3)
        - name: sensor2
          register: tcptest.1.3
          register_type: input
          converter: std.divide(10,2)
```
