### ISSUE TITLE
Modbus TCP reconnect issue

### ISSUE THREAD

**Issue by JayHerpin** [BlackZork/mqmgateway#39]
Steps to reproduce:

Computer and device are both connected via a simple switch. Run the configuration below. Disconnect the device from the switch (or cut its power). Wait for some period of time then reconnect the ethernet or restore power.

At this point the connection doesn't recover.

What is observed:

![image](https://github.com/BlackZork/mqmgateway/assets/159202566/74a4d63e-4399-40d6-83af-7a64119b2533)

Notice the packet trace on the right.  You can see at time 1713450984.766486 I reconnected the device, but at this point the sliding window never progresses further... 

What should Happen:

Frankly, libmodbus should be handling this... and I do believe this is a libmodbus bug... actually now that I am typing this  I am wondering if this is fixed in a newer version... however:

I was wondering if you would be opposed to me adding in some application level guards against this sort of timeout? Basically a separate higher application level timeout to guard against libmodbus errors in the event we don't get any sort of response back within the given time by forcefully resetting the whole modbus connection.

(excuse me being lazy for not making this  a separate bug/pull request but...) bonus bug:

The modbus timeout parameters are not being set for TCP connections, eg:

![image](https://github.com/BlackZork/mqmgateway/assets/159202566/fe4b46d5-ad01-43aa-8aae-9272668d4636)

And also, the default value of 1s is not actually a valid value for the modbus timeout parameters:

https://github.com/stephane/libmodbus/blob/master/docs/modbus_set_response_timeout.md

the max is 999999 us

-------------------------------------------------------------------

OS: ubuntu 22.04
Libmodbus version: libmodbus5-3.1.6-2
Device: https://www.advantech.com/en-us/products/a67f7853-013a-4b50-9b20-01798c56b090/adam-6066/mod_e256cafc-36dd-4740-86a0-d7e53b5c4ddf

Configuration (abbreviated):
```

modmqttd:
  # converter_search_path:
  #   - /usr/lib/modmqttd/
  # converter_plugins:
  # - stdconv.so
  # - exprconv.so
modbus:
  networks:
    - name: adam
      address: 192.168.2.2
      port: 502
      response_timeout: 200ms
      response_data_timeout: 200ms
      slaves:
        - address: 0
          delay_before_first_poll: 50ms
          poll_groups:
            - register: 1
              register_type: coil
              count: 6
            - register: 17
              register_type: coil
              count: 6

mqtt:
  client_id: modbus
  refresh: 1s
  broker:
    host: localhost
    port: 1883
    keepalive: 60
  objects:
    - topic: winch/anchor/manual_ctrl
      network: adam
      slave: 0
      refresh: 200ms
      state:
        register: 1
        register_type: coil
```
