### ISSUE TITLE
Error processing network traffic: Invalid function arguments provided

### ISSUE THREAD

**Issue by mczerski** [BlackZork/mqmgateway#48]
I get this error when trying to use modmqttd and have no clue what is wrong.
I'm using mosquitto as broker started like that:
```
docker run -p 1883:1883 -d --rm eclipse-mosquitto
```
modmqttd config:
```
modmqttd:
  converter_search_path:
    - /usr/lib/modmqttd
  converter_plugins:
    - stdconv.so
modbus:
  networks:
    - name: rtutest
      device: /dev/ttyUSB0
      baud: 115200
      parity: N
      data_bit: 8
      stop_bit: 1
mqtt:
  client_id: modbus
  #refresh: 1ms
  broker:
    host: localhost
  objects:
    - topic: test
      state:
        name: led
        register: rtutest.1.1
        register_type: coil
```
stdout of modmqttd:
```
2024-May-17 08:13:40.140977: [INFO ] modmqttd is starting
2024-May-17 08:13:40.141765: [INFO ] Added converter plugin std
2024-May-17 08:13:40.143092: [INFO ] Connecting to localhost:1883
2024-May-17 08:13:40.143256: [INFO ] Creating RTU context: /dev/ttyUSB0, 115200-8N1
2024-May-17 08:13:40.143313: [INFO ] Response timeout set to 500ms
2024-May-17 08:13:40.143517: [INFO ] modbus: connecting
2024-May-17 08:13:40.143675: [INFO ] Disconnected from mqtt broker, code:The connection was lost.
2024-May-17 08:13:40.143731: [INFO ] reconnecting to mqtt broker
2024-May-17 08:13:40.211149: [INFO ] modbus: connected
2024-May-17 08:13:40.211288: [INFO ] Waiting for mqtt network to become online
2024-May-17 08:13:40.211309: [INFO ] Connecting to localhost:1883
2024-May-17 08:13:40.211351: [INFO ] Waiting for mqtt network to become online
2024-May-17 08:13:40.211602: [ERROR] Error processing network traffic: Invalid function arguments provided.
2024-May-17 08:13:40.211924: [INFO ] Disconnected from mqtt broker, code:The connection was lost.
2024-May-17 08:13:40.212069: [INFO ] reconnecting to mqtt broker
2024-May-17 08:13:40.212121: [INFO ] Waiting for mqtt network to become online
```
