### ISSUE TITLE
named map should allow to use converters that handles multiple registers as input

### ISSUE THREAD

**Issue by BlackZork** [BlackZork/mqmgateway#49]
This should be possible to define as mqtt topic:

```
  objects:
    - topic: test_state
      state:
        - name: sensor1
          register: tcptest.1.2
          register_type: input
          count: 2
          converter: std.int32()
        - name: sensor2
          register: tcptest.1.3
          register_type: input
          converter: std.divide(10,2)
```

output: ```{ "sensor1": "<converted int32">, "sensor2": "divided val" }``` 

Currently it works for divide but for int32 throw conf exception "count is disallowed".
