### ISSUE TITLE
configuraition issue

### ISSUE THREAD

**Issue by mczerski** [BlackZork/mqmgateway#66]
I/m using v2.8.1
This is my config:
```
modmqttd:
  converter_search_path:
    - /usr/lib/modmqttd
  converter_plugins:
    - stdconv.so
modbus:
  networks:
    - name: rtugpio
      response_timeout: 50ms
      response_data_timeout: 50ms
      device: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
      # serial port parameters
      baud: 9600
      parity: N
      data_bit: 8
      stop_bit: 1
      delay_before_command: 10ms
mqtt:
  client_id: modbus
  refresh: 100ms
  broker:
    host: localhost
  objects:
    - topic: modbus/gpio
      network: rtugpio
      slave: 1
      state:
        register: 1
        register_type: bit
        count: 16
    - topic: modbus/kitchen_motion
      network: rtugpio
      slave: 2
      state:
        register: 2
        register_type: holding
    - topic: modbus/livingroom_led_dimmer/level
      network: rtugpio
      slave: 3
      state:
        register: 1
        register_type: input
      commands:
        - name: set
          register: 1
          register_type: holding
    - topic: modbus/livingroom_scene/1
      network: rtugpio
      slave: 3
      state:
        register: 2
        register_type: input
    - topic: modbus/livingroom_scene/2
      network: rtugpio
      slave: 3
      state:
        register: 3
        register_type: input
```

The problem is that under topics modbus/livingroom_scene/1 and modbus/livingroom_scene/2 there is always value of the register 1 and not the configured register for each topic.
What I want to achive is to have values of the first 3 input register of the slave 3 on separate mqtt topics. Should I write my config in different way ?
