### ISSUE TITLE
Publish timestamp along with modbus data

### ISSUE THREAD

**Issue by dakhnod** [BlackZork/mqmgateway#67]
Is there a way of publishing a timestamp along with the modbus values via mqtt?
So that the MQTT payload looks something like
```json
{
  "irradiance":10,
  "temp_cell_leg_1":517,
  "temp_ext_leg_1":0,
  "wind_speed":0,
  "reserved":0,
  "temp_cell_leg_2":1267,
  "temp_ext_leg_2":0,
  "temp_cell":26.7, 
  "timestamp": 1727276050676
}
```

**Comment by BlackZork** [comment]
Not yet. What kind of timestamp do you need? Seconds since epoch in local time zone? Do you need milliseconds/microseconds precision?

**Comment by dakhnod** [comment]
Hmm...millis should suffice. How about something like a dummy register with `converter: std.epoch_millis()` or something?

Also, is it possible to provide a list of converters for stacking them?

**Comment by BlackZork** [comment]
Yes, the simplest method would be to add std.timestamp(format="") with strftime() like formats extended with milli and microsecond modifiers. 

Converter needs list of register values as input and returns [MqttValue](https://github.com/BlackZork/mqmgateway/blob/04f618bd287ab2c6e3d1c41bd40a1b91ee84ccb4/libmodmqttconv/mqttvalue.hpp#L9) as output - this interface makes stacking impossible. If you need to perform multiple conversions or math it is better to use expr plugin.

I have not tested it, but it should be possible to add a timestamp converter to dict member like this:

```
state:
  registers:
    - name: my_value
      register: 1
      register_type: input
    - name: ts
      register: 1
      register_type: input
      converter: std.timestamp()
```

This should output ```{ "my_value": 12, "ts": 1242424244 }. Still a hack, because timestamp will be updated on every mqtt payload creation, not when the register 1 was last read as I would expect.

**Comment by dakhnod** [comment]
Okay, thanks for the suggestion! It would indeed be better though if the timestamp was set when the group of registers was read...

**Comment by BlackZork** [comment]
It will work in most cases, because mqtt payload creation is triggered when at least one related register value is changed (or every poll if you set `publish_mode` to `every_poll`).

It will not work if you specify different registers for data and timestamp and set different refresh times in modbus section for them like this:

```
modbus:
  networks:
    - name: tcptest
      address: localhost
      port: 501
      slaves:
        - address: 1
          poll_groups:
            - register: 1
              register_type: input
              refresh: 10ms
            - register: 2
              register_type: input
              refresh: 1s
```

and in state:

```state:
  registers:
    - name: my_value
      register: tcptest.1.1
      register_type: input
    - name: ts
      register: tcptest.1.2
      register_type: input
      converter: std.timestamp()
```

Mqtt payload will be generated every 10ms, so `ts` will be updated every 10ms.

No idea if this makes any sense in real life, but I think one would expect timestamp to be updated after register 2 was read (every 1s), not any register used to create mqtt payload.
