### ISSUE TITLE
global delay_before_command not respected in poll_groups

### ISSUE THREAD

**Issue by mczerski** [BlackZork/mqmgateway#70]
used version: v2.10.0
config (at the end)
In attached config, if delay_before_command was not defined for poll_groups in slaves section then those slaves would communicate without any delay between command. If this is intentional then it is counter-intuitive.
```
modmqttd:
  converter_search_path:
    - /usr/lib/modmqttd
  converter_plugins:
    - stdconv.so
modbus:
  networks:
    - name: rtugpio
      response_timeout: 50ms
      response_data_timeout: 50ms
      device: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
      # serial port parameters
      baud: 9600
      parity: N
      data_bit: 8
      stop_bit: 1
      delay_before_command: 10ms
      slaves:
        - address: 3
          delay_before_command: 10ms
          poll_groups:
            - register: 1
              register_type: input
              count: 10
        - address: 4
          delay_before_command: 10ms
          poll_groups:
            - register: 1
              register_type: input
              count: 10
        - address: 5
          delay_before_command: 10ms
          poll_groups:
            - register: 1
              register_type: input
              count: 10
mqtt:
  client_id: modbus
  refresh: 100ms
  broker:
    host: localhost
  objects:
    - topic: modbus/gpio
      network: rtugpio
      slave: 1
      state:
        register: 1
        register_type: bit
        count: 16
    - topic: modbus/kitchen_motion
      network: rtugpio
      slave: 2
      state:
        register: 11
        register_type: input
    - topic: modbus/livingroom_led_dimmer/level
      network: rtugpio
      slave: 3
      state:
        register: 1
        register_type: input
      commands:
        - name: set
          register: 1
          register_type: holding
    - topic: modbus/livingroom_scene/1
      network: rtugpio
      slave: 3
      state:
        register: 5
        register_type: input
    - topic: modbus/livingroom_scene/2
      network: rtugpio
      slave: 3
      state:
        register: 6
        register_type: input
    - topic: modbus/livingroom_spot_dimmer/level
      network: rtugpio
      slave: 4
      state:
        register: 1
        register_type: input
      commands:
        - name: set
          register: 1
          register_type: holding
    - topic: modbus/livingroom_scene/3
      network: rtugpio
      slave: 4
      state:
        register: 5
        register_type: input
    - topic: modbus/livingroom_scene/4
      network: rtugpio
      slave: 4
      state:
        register: 6
        register_type: input
    - topic: modbus/kitchen_spot_dimmer/level
      network: rtugpio
      slave: 5
      state:
        register: 1
        register_type: input
      commands:
        - name: set
          register: 1
          register_type: holding
    - topic: modbus/kitchen_scene/1
      network: rtugpio
      slave: 5
      state:
        register: 5
        register_type: input
    - topic: modbus/kitchen_scene/2
      network: rtugpio
      slave: 5
      state:
        register: 6
        register_type: input
```
