### ISSUE TITLE
Make network name optional for topic definition if it can be figured out from config.

### ISSUE THREAD

**Issue by BlackZork** [BlackZork/mqmgateway#72]
If poll groups are defined and slaves have distinct addresses across modbus networks, then figure out network name from slave address:

```
modbus:
  - name: port1
    slaves:
       - address: 1
  - name: port2
    slaves:
       - address: 10
mqtt:
 - topic: /some/topic
   slave: 10
```

`/some/topic/` polls from port2 network, because slave 10 is configured there.

If there is only one modbus network defined then there should be no need to declare a network name for a topic.
