### ISSUE TITLE
Issues using std.multiply converter

### ISSUE THREAD

**Issue by dakhnod** [BlackZork/mqmgateway#87]
When running this minimal config
```
modmqttd:
  converter_search_path:
    - build/stdconv
    - build/exprconv
  converter_plugins:
    - stdconv.so
    - exprconv.so
modbus:
  networks:
    - name: test
      address: 127.0.0.1
      port: 5020
mqtt:
  client_id: modbus
  refresh: 3s
  publish_mode: every_poll
  broker:
    host: 127.0.0.1
    port: 1883
  objects:
    - topic: v1/test
      network: test
      slave: 1
      state:
        - register: "0x8724"
          register_type: holding
          name: value
          converter: std.multiply(10)
```

I am getting this error:
```
modmqttd: /usr/include/rapidjson/internal/dtoa.h:217: char* rapidjson::internal::dtoa(double, char*, int): Assertion `maxDecimalPlaces >= 1' failed.
```

Using `expr.evaluate(R0 * 10)` instead works, weird...

In any case, thanks for your work!
